### ISSUE TITLE
And invalid fen will make the game unplayable after a move

### ISSUE THREAD

**Issue by o-k-a-y** [maksimKorzh/wukongJS#7]
Should be an easy fix, but just wanted to make you aware.

1. Make any number of moves or none at all
2. Change fen to invalid string
3. Make a move

**Comment by maksimKorzh** [comment]
See reply in the previous issue and please don't open multiple issues on the same topic

**Comment by o-k-a-y** [comment]
I feel this one is a different topic. Maybe you've misunderstood what I meant here.
![fen](https://user-images.githubusercontent.com/22223097/111346467-25995200-8676-11eb-9fb6-7e4dd4da7af3.png)

**Comment by maksimKorzh** [comment]
Well, that happens because I don't have fen validation.
As far as:
1. Make any number of moves or none at all
2. Change fen to invalid string
3. Make a move

Doesn't really make sense (why to input invalid FEN?) I don't see the reason to deal with this.
My youtube projects are more for demo purposes.

I go for them more seriously when it's a paid job and when my code works in production,
e.g. here's my Chinese chess engine written in JS (Wukong's clone for xiangqi) is used
for "play with computer" mode:
https://play.xiangqi.com/lobby

Hope it explains my position)
